// 📁 Lecture 10 Notes (Cleaned and Explained)
// 👤 User Model (UserActivation.model.js)
// js
// Copy code
// {
//   _id: ObjectId (automatically generated by MongoDB),
//   watchHistory: [ObjectId], // References to Video IDs
//   username: String,
//   email: String,
//   fullName: String,
//   avatar: String,      // URL of the profile image
//   coverImage: String,  // URL of the cover image
//   password: String,    // Hashed password
//   refreshToken: String,
//   createdAt: Date,
//   updatedAt: Date
// }
// ✅ Note: We don’t explicitly define id because MongoDB automatically creates a unique _id using BSON format (Binary JSON).

// 🎥 Video Model (video.model.js)
// js
// Copy code
// {
//   _id: ObjectId,
//   videoFile: String,     // URL from cloud storage (e.g., AWS, Cloudinary)
//   thumbnail: String,     // Thumbnail image URL
//   owner: ObjectId,       // Reference to User
//   title: String,
//   description: String,
//   duration: Number,
//   views: Number,
//   isPublished: Boolean,
//   createdAt: Date,
//   updatedAt: Date
// }
// ☁️ Uploading Avatars, Cover Images, and Videos
// We use third-party services (like AWS S3, Cloudinary, etc.) to upload files.

// When we upload, the service returns a URL of the uploaded file.

// That URL is stored as a string in our MongoDB document (e.g., avatar, coverImage, videoFile, thumbnail).

// 💡 We do not store actual files in MongoDB, only their URLs.

// 👀 Watch History Tracking
// In the user model, we maintain a watchHistory array.

// It contains an array of Video IDs (ObjectId).

// Whenever a user watches a video, we push its ID into this array.

// 🔍 Indexing in MongoDB
// If you want to optimize a field for faster search, you use:

// js
// Copy code
// { fieldName: { type: String, index: true } }
// 📌 Indexing makes querying/searching faster, especially on large datasets.

// 🧱 Aggregation Pipeline in MongoDB
// In real-world apps, we often need to filter, group, count, paginate, and do more advanced querying.

// That’s where MongoDB Aggregation comes in.

// It uses a pipeline structure where each stage processes the data.

// 📦 Mongoose Aggregation Plugin

// npm install mongoose-aggregate-paginate-v2
// This plugin helps paginate the results of aggregation queries.

// Widely used in production applications.

// 🔐 Password Hashing with bcrypt
// We never store plain passwords. Instead, we hash them.

// bcrypt and bcryptjs are two popular libraries.

// bcryptjs is a pure JavaScript version, lighter and zero-dependency.

// bcrypt uses C++ bindings, so it's faster, but needs native dependencies.

// 🔁 Use Case:
// Hash password before saving to DB

// On login, compare entered password with hashed password using bcrypt.compare()

// 🪙 JWT and Refresh Tokens
// 📌 Why Tokens?
// We use JWTs (JSON Web Tokens) for authentication. Once a user logs in:

// The backend creates a JWT token and sends it to the frontend.

// The frontend includes this token in future API requests (usually in headers).

// 🔐 Structure of JWT
// A JWT has 3 parts:

// css
// Copy code
// [ Header ] . [ Payload ] . [ Signature ]
// Header – Specifies the algorithm used (e.g., HS256).

// Payload – Contains the data (e.g., user ID, email, etc.)

// Signature – Created using a secret key, used to verify the token.

// You can view and decode JWTs on https://jwt.io.

// 🔒 Without the secret key, you can’t create or verify valid tokens — this is what keeps them secure.

// 🔄 Refresh Tokens
// JWTs usually expire quickly (e.g., 15 minutes).

// A refresh token is a long-lived token that allows the frontend to get a new JWT without re-logging in.

// Refresh tokens are:

// Stored in the user model (refreshToken)

// Often stored securely in cookies on the frontend

// 🧠 Summary
// Concept	Description
// User & Video Models	Store relationships using ObjectIds
// Avatar & Video Uploads	Use 3rd-party cloud storage; store URLs in MongoDB
// Watch History	Array of video IDs watched by user
// Indexing	Use index: true for faster search
// Aggregation	Advanced data queries (grouping, counting, filtering)
// bcrypt / bcryptjs	Securely hash and verify passwords
// JWT	Secure, encrypted token for authentication
// Refresh Token	Long-term token to regenerate JWT after it expires
Introduction to bcrypt and its role in
password hashing, highlighting its similarity
to other hashing methods.
Explanation of bcrypt as a library that
encrypts passwords to prevent storing
them in clear text, ensuring secure
password management.
Overview of JSON Web Tokens (JWT) as a
basic library for creating tokens based on
cryptography, essential for secure data
handling.
verview of JSON Web Tokens (JWT) as a
basic library for creating tokens based on
ryptography, essential for secure data
handling.
Description of how JWTs are structured,
including headers and payload, and the
importance of cryptographic algorithms in
nsuring data security.
lick to collapse A
he video discusses the process of password
ncryption and the importance of managing
password changes effectively to ensure
ecurity.
Proposed solution to only encrypt the
password when it is modified, preventing
unnecessary changes to the password
during other updates.
Click to collapse A
This section discusses the concept of JSON
Web Tokens (JWT), explaining their purpose as
bearer tokens, their security aspects, and how
to create and manage them effectively.
Introduction to JWT and its significance as
a bearer token, emphasizing its role in
authentication
Introduction to JWT and its significance as
bearer token, emphasizing its role in
uthentication.
Explanation of what a bearer token is,
escribing it as a key that grants access to
resources and the importance of keeping it
ecure.
verview of the process to create JWTs,
including necessary variables and how
libraries facilitate this task.
Instructions on how to understand and
utilize JWTs, highlighting user-friendly
resources and tools available online.
Details on the configuration of JWTs,
including the use of private keys and
setting expiration times for tokens.
lick to collapse A
This section focuses on the generation and
usage of access tokens, specifically JWTs
(JSON Web Tokens). It explains the differences
between two types of tokens, the process of
generating a token, and the necessary
components involved in creating a payload for
the token.
Introduction to access tokens and their
types, emphasizing that there is no
// direct encryption ->not posssible
// //we need to take from mongoose like hooks in mws
// //pre->execute one after another after each individual care 
// // as soon as the data ig getting saveed just before that 
// if any user has wriitten a call or a controller 
// that save this data just before  
// just do smthg before saving the data'
// here we encrypt the password .so we have hooks for this,
//  userSchema.pre()
//  we have so many events 
//   ValidityState,save,removeone,updateone,deleteone,,intit 
//   then callback ->dont use here as it  wont gives the context of the
//    current as it is a callback in js ->that is this keyword is missing ->but context ref is most iportatnt here
//    userSchema.pre("save",async function (next){
//     if((!this.password.isModified()))return next();
//      this.password=bcrypt.hash(this.password,10);
//      next();
//    })

// what if we the user given passsword is correct or not we need to create a controlleer for this
// here the passsword is encrypted  
// but the user inputs the normal data then how do you compare them whether the user has entered the correct passwor do not  

// we create the custom methods 
// userSchema.methhods.ispasswordsCorrect=async function (password){
//   bcrypt.compare(password,this.password);
// }
// //give me the password whoever i called, this method will send the clear text passsword 
// // or i can access a password form this because just like the password has access to all its objects 
// before they store in th edb similarly methods have also access4 
// this.password->encrypted one ->cryptography ->computation power
// so takes time 
// userSchema.methhods.ispasswordsCorrect=async function (password){
//   return await bcrypt.compare(password,this.password);
// }

// jwt?
// it is a bearer token
// means that the one who bears it ,accepts it
// whoever ha sthis token ,whoever  sends it to me , i 
// will send the data to him 
// it is like a key so dont lose the key. 
// it's  quite tsrong but one has to take of tokens 
// we see this variable in .env file 
// aceess_token_secret =in production we use complex strings
// secret is strong a sit a complex. 
// aceesss _tokren_expiriy syntax
// is 1 day 
 
// refresh token? 
// refresh_toen_secret=complex-string 
// refresh token expiriy=10 days  

// we will be using both sessions and cookies ,we r going with a lot of security
// so our access token will not be stored inthe db 
// but the  refresh_token is stored inthe db ,this is how it works ,
//  copy all the tokens and even put it in saaample file .env 
//  can i make the make the method to make the access tokn in this way? like the methods we had creed earlier?  
//  which makes easy in future 

//  userSchema.addmethods.generateaccesstoken=function(){
//   //sign methd to generate the token 
//   return jwt.sign()
//   //inside sign there ll be payload,obj,buffer ,and you nneed a secret key and there is a lot of options like signing 
//   {//what information do i want you to keep 
//     _id:this_id,//this method already saved in database  and they have all the access 
//     //we et it from mongodb
//     email:this.email,
//     username:this.users,fullname:fullname
//   }
//   process.env.accesstokensecret,
//   {
//     expiresIn:process.env.acessstoken _expiriy 
//   }
//   {

//   }
//  }
//  userSchema.addmethods.generatrefreshtoken=function(){}
// both are jwt tokens 
// usage is diff 
// // ✅ User Schema & Authentication in Mongoose (FULL NOTES)

// // 👉 Export the model
// module.exports = mongoose.model("User", userSchema);

// // ❌ Direct encryption of password is not possible when saving data in MongoDB
// // ✅ Solution: Use **Mongoose middleware (hooks)**

// // ------------------------
// // 🔒 Password Encryption
// // ------------------------

// // ➤ Mongoose provides hooks like `.pre()` to run logic before certain operations
// // ➤ We want to encrypt the password just **before the data is saved**

// /*
// ✅ Available Mongoose Hook Events:
// - validate
// - save
// - remove
// - updateOne
// - deleteOne
// - init
// */

// // ❌ Don't use callbacks with hooks like pre("save")
// //    → Because `this` will lose context in a JS callback
// // ✅ Use async functions to maintain `this` (current document)

// // Encrypt password using bcrypt before saving to DB
// userSchema.pre("save", async function (next) {
//   // Only encrypt if password is newly added or modified
//   if (!this.isModified("password")) return next();

//   // Encrypt the password with salt rounds = 10
//   this.password = await bcrypt.hash(this.password, 10);
//   next();
// });

// // ----------------------------
// // 🔐 Password Verification
// // ----------------------------

// // ➤ User enters plain text password
// // ➤ We compare it with the hashed password stored in the DB

// userSchema.methods.isPasswordCorrect = async function (password) {
//   return await bcrypt.compare(password, this.password);
// };

// // 📌 Why this works?
// // - `this.password` refers to the encrypted password in DB
// // - `.methods` has access to the document's fields (just like in the hook)
// // - The method will be available on all user objects from the model

// // ⚠️ bcrypt is cryptography-based → takes CPU time (due to hashing complexity)

// // -------------------------------------
// // 🔐 JSON Web Token (JWT) Integration
// // -------------------------------------

// // 📦 JWT = Bearer Token Authentication
// // ➤ Whoever "bears" the token is assumed authenticated
// // ➤ If token is valid, user is trusted
// // ➤ Used to send/receive data securely (like a digital key)

// // 🗝 Access Token:
// // - Short-lived (e.g., 1 day)
// // - ✅ NOT stored in DB (stored in browser memory or HTTP-only cookies)

// // 🗝 Refresh Token:
// // - Longer-lived (e.g., 10 days)
// // - ✅ STORED in DB (so that it can be verified and revoked)

// // ✅ These secrets should be kept in the `.env` file

// /*
// .env file example:

// ACCESS_TOKEN_SECRET = your-access-secret-key
// ACCESS_TOKEN_EXPIRY = 1d
// REFRESH_TOKEN_SECRET = your-refresh-secret-key
// REFRESH_TOKEN_EXPIRY = 10d
// */

// // ------------------------------
// // 🧠 Custom JWT Generator Methods
// // ------------------------------

// // ➤ Creating a method to generate Access Token
// userSchema.methods.generateAccessToken = function () {
//   return jwt.sign(
//     {
//       _id: this._id,
//       email: this.email,
//       username: this.username,
//       fullName: this.fullName,
//     },
//     process.env.ACCESS_TOKEN_SECRET,
//     {
//       expiresIn: process.env.ACCESS_TOKEN_EXPIRY,
//     }
//   );
// };

// // ➤ Creating a method to generate Refresh Token
// userSchema.methods.generateRefreshToken = function () {
//   return jwt.sign(
//     {
//       _id: this._id,
//     },
//     process.env.REFRESH_TOKEN_SECRET,
//     {
//       expiresIn: process.env.REFRESH_TOKEN_EXPIRY,
//     }
//   );
// };

// // -------------------------
// // 📌 Summary of Key Concepts
// // -------------------------

// // 🔑 Mongoose pre-save hook → encrypt password before saving
// // 🔑 bcrypt.compare() → checks if entered password is correct
// // 🔑 Instance methods like `isPasswordCorrect()` or `generateAccessToken()` 
// //    have access to current user (`this` keyword)
// // 🔑 Access Token: short-lived, NOT stored in DB
// // 🔑 Refresh Token: longer-lived, STORED in DB for security
// // 🔑 JWT Tokens generated using jwt.sign(payload, secret, options)
// // 🔑 All secrets and expiry values should be kept secure in .env



// // direct encryption ->not posssible
// //we need to take from mongoose like hooks in mws
// //pre->execute one after another after each individual care 
// // as soon as the data ig getting saveed just before that 
// if any user has wriitten a call or a controller 
// that save this data just before  
// just do smthg before saving the data'
// here we encrypt the password .so we have hooks for this,
//  userSchema.pre()
//  we have so many events 
//   ValidityState,save,removeone,updateone,deleteone,,intit 
//   then callback ->dont use here as it  wont gives the context of the
//    current as it is a callback in js ->that is this keyword is missing ->but context ref is most iportatnt here
//    userSchema.pre("save",async function (next){
//     if((!this.password.isModified()))return next();
//      this.password=bcrypt.hash(this.password,10);
//      next();
//    })

// what if we the user given passsword is correct or not we need to create a controlleer for this
// here the passsword is encrypted  
// but the user inputs the normal data then how do you compare them whether the user has entered the correct passwor do not  

// we create the custom methods 
// userSchema.methhods.ispasswordsCorrect=async function (password){
//   bcrypt.compare(password,this.password);
// }
// //give me the password whoever i called, this method will send the clear text passsword 
// // or i can access a password form this because just like the password has access to all its objects 
// before they store in th edb similarly methods have also access4 
// this.password->encrypted one ->cryptography ->computation power
// so takes time 
// userSchema.methhods.ispasswordsCorrect=async function (password){
//   return await bcrypt.compare(password,this.password);
// }

// jwt?
// it is a bearer token
// means that the one who bears it ,accepts it
// whoever ha sthis token ,whoever  sends it to me , i 
// will send the data to him 
// it is like a key so dont lose the key. 
// it's  quite tsrong but one has to take of tokens 
// we see this variable in .env file 
// aceess_token_secret =in production we use complex strings
// secret is strong a sit a complex. 
// aceesss _tokren_expiriy syntax
// is 1 day 
 
// refresh token? 
// refresh_toen_secret=complex-string 
// refresh token expiriy=10 days  

// we will be using both sessions and cookies ,we r going with a lot of security
// so our access token will not be stored inthe db 
// but the  refresh_token is stored inthe db ,this is how it works ,
//  copy all the tokens and even put it in saaample file .env 
//  can i make the make the method to make the access tokn in this way? like the methods we had creed earlier?  
//  which makes easy in future 

//  userSchema.addmethods.generateaccesstoken=function(){
//   //sign methd to generate the token 
//   return jwt.sign()
//   //inside sign there ll be payload,obj,buffer ,and you nneed a secret key and there is a lot of options like signing 
//   {//what information do i want you to keep 
//     _id:this_id,//this method already saved in database  and they have all the access 
//     //we et it from mongodb
//     email:this.email,
//     username:this.users,fullname:fullname
//   }
//   process.env.accesstokensecret,
//   {
//     expiresIn:process.env.acessstoken _expiriy 
//   }
//   {

//   }
//  }
//  userSchema.addmethods.generatrefreshtoken=function(){}
// both are jwt tokens 
// usage is diff 
// // ✅ User Schema & Authentication in Mongoose (FULL NOTES)

// // 👉 Export the model
// module.exports = mongoose.model("User", userSchema);

// // ❌ Direct encryption of password is not possible when saving data in MongoDB
// // ✅ Solution: Use **Mongoose middleware (hooks)**

// // ------------------------
// // 🔒 Password Encryption
// // ------------------------

// // ➤ Mongoose provides hooks like `.pre()` to run logic before certain operations
// // ➤ We want to encrypt the password just **before the data is saved**

// /*
// ✅ Available Mongoose Hook Events:
// - validate
// - save
// - remove
// - updateOne
// - deleteOne
// - init
// */

// // ❌ Don't use callbacks with hooks like pre("save")
// //    → Because `this` will lose context in a JS callback
// // ✅ Use async functions to maintain `this` (current document)

// // Encrypt password using bcrypt before saving to DB
// userSchema.pre("save", async function (next) {
//   // Only encrypt if password is newly added or modified
//   if (!this.isModified("password")) return next();

//   // Encrypt the password with salt rounds = 10
//   this.password = await bcrypt.hash(this.password, 10);
//   next();
// });

// // ----------------------------
// // 🔐 Password Verification
// // ----------------------------

// // ➤ User enters plain text password
// // ➤ We compare it with the hashed password stored in the DB

// userSchema.methods.isPasswordCorrect = async function (password) {
//   return await bcrypt.compare(password, this.password);
// };

// // 📌 Why this works?
// // - `this.password` refers to the encrypted password in DB
// // - `.methods` has access to the document's fields (just like in the hook)
// // - The method will be available on all user objects from the model

// // ⚠️ bcrypt is cryptography-based → takes CPU time (due to hashing complexity)

// // -------------------------------------
// // 🔐 JSON Web Token (JWT) Integration
// // -------------------------------------

// // 📦 JWT = Bearer Token Authentication
// // ➤ Whoever "bears" the token is assumed authenticated
// // ➤ If token is valid, user is trusted
// // ➤ Used to send/receive data securely (like a digital key)

// // 🗝 Access Token:
// // - Short-lived (e.g., 1 day)
// // - ✅ NOT stored in DB (stored in browser memory or HTTP-only cookies)

// // 🗝 Refresh Token:
// // - Longer-lived (e.g., 10 days)
// // - ✅ STORED in DB (so that it can be verified and revoked)

// // ✅ These secrets should be kept in the `.env` file

// /*
// .env file example:

// ACCESS_TOKEN_SECRET = your-access-secret-key
// ACCESS_TOKEN_EXPIRY = 1d
// REFRESH_TOKEN_SECRET = your-refresh-secret-key
// REFRESH_TOKEN_EXPIRY = 10d
// */

// // ------------------------------
// // 🧠 Custom JWT Generator Methods
// // ------------------------------

// // ➤ Creating a method to generate Access Token
// userSchema.methods.generateAccessToken = function () {
//   return jwt.sign(
//     {
//       _id: this._id,
//       email: this.email,
//       username: this.username,
//       fullName: this.fullName,
//     },
//     process.env.ACCESS_TOKEN_SECRET,
//     {
//       expiresIn: process.env.ACCESS_TOKEN_EXPIRY,
//     }
//   );
// };

// // ➤ Creating a method to generate Refresh Token
// userSchema.methods.generateRefreshToken = function () {
//   return jwt.sign(
//     {
//       _id: this._id,
//     },
//     process.env.REFRESH_TOKEN_SECRET,
//     {
//       expiresIn: process.env.REFRESH_TOKEN_EXPIRY,
//     }
//   );
// };

// // -------------------------
// // 📌 Summary of Key Concepts
// // -------------------------

// // 🔑 Mongoose pre-save hook → encrypt password before saving
// // 🔑 bcrypt.compare() → checks if entered password is correct
// // 🔑 Instance methods like `isPasswordCorrect()` or `generateAccessToken()` 
// //    have access to current user (`this` keyword)
// // 🔑 Access Token: short-lived, NOT stored in DB
// // 🔑 Refresh Token: longer-lived, STORED in DB for security
// // 🔑 JWT Tokens generated using jwt.sign(payload, secret, options)
// // 🔑 All secrets and expiry values should be kept secure in .env

